# Generated by Django 5.1.3 on 2024-12-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='categories'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='categories'),
        ),
    ]
