# Generated by Django 5.1.3 on 2024-12-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_description_category_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='categories/image_1'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='categories/image_2'),
        ),
    ]
